server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # 第一个路由规则 short-link-admin
        - id: short-link-admin
          uri: lb://short-link-admin/api/short-link/admin/**
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            # 使用 TokenValidate 过滤器，用于验证请求的合法性
            - name: TokenValidate
              args:
                # 设置白名单，指定不需要进行 Token 验证的路径
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username

        # 第二个路由规则 short-link-project
        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            # 使用 TokenValidate 过滤器，用于验证请求的合法性
            - name: TokenValidate
