server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: aggregation
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
